
/*
 * 
 */

package org.savara.examples.store;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-08-10T09:46:11.543+01:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "StoreService", 
                  wsdlLocation = "wsdl/PurchaseGoods_Store.wsdl",
                  targetNamespace = "http://www.savara.org/examples/Store") 
public class StoreService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.savara.org/examples/Store", "StoreService");
    public final static QName StorePort = new QName("http://www.savara.org/examples/Store", "StorePort");
    static {
        URL url = null;
        try {
            url = new URL("wsdl/PurchaseGoods_Store.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StoreService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "wsdl/PurchaseGoods_Store.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StoreService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StoreService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StoreService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns Store
     */
    @WebEndpoint(name = "StorePort")
    public Store getStorePort() {
        return super.getPort(StorePort, Store.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Store
     */
    @WebEndpoint(name = "StorePort")
    public Store getStorePort(WebServiceFeature... features) {
        return super.getPort(StorePort, Store.class, features);
    }

}
