//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.24 at 10:46:42 AM BST 
//


package org.savara.activity.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.savara.activity.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Activity_QNAME = new QName("http://www.savara.org/activity", "activity");
    private final static QName _ActivityList_QNAME = new QName("http://www.savara.org/activity", "activityList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.savara.activity.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link ActivityList }
     * 
     */
    public ActivityList createActivityList() {
        return new ActivityList();
    }

    /**
     * Create an instance of {@link Correlation }
     * 
     */
    public Correlation createCorrelation() {
        return new Correlation();
    }

    /**
     * Create an instance of {@link InteractionActivity }
     * 
     */
    public InteractionActivity createInteractionActivity() {
        return new InteractionActivity();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link CorrelationKey }
     * 
     */
    public CorrelationKey createCorrelationKey() {
        return new CorrelationKey();
    }

    /**
     * Create an instance of {@link ComponentId }
     * 
     */
    public ComponentId createComponentId() {
        return new ComponentId();
    }

    /**
     * Create an instance of {@link ProtocolAnalysis }
     * 
     */
    public ProtocolAnalysis createProtocolAnalysis() {
        return new ProtocolAnalysis();
    }

    /**
     * Create an instance of {@link Context }
     * 
     */
    public Context createContext() {
        return new Context();
    }

    /**
     * Create an instance of {@link Analysis }
     * 
     */
    public Analysis createAnalysis() {
        return new Analysis();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Activity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.savara.org/activity", name = "activity")
    public JAXBElement<Activity> createActivity(Activity value) {
        return new JAXBElement<Activity>(_Activity_QNAME, Activity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivityList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.savara.org/activity", name = "activityList")
    public JAXBElement<ActivityList> createActivityList(ActivityList value) {
        return new JAXBElement<ActivityList>(_ActivityList_QNAME, ActivityList.class, null, value);
    }

}
