//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.31 at 07:35:14 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.savara.org/scenario/simulation", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.savara.scenario.simulation.model;
