//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.31 at 07:35:14 PM BST 
//


package org.savara.scenario.simulation.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoleDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoleDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="scenarioRole" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="model" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="modelRole" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="simulator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoleDetails")
public class RoleDetails {

    @XmlAttribute
    protected String scenarioRole;
    @XmlAttribute
    protected String model;
    @XmlAttribute
    protected String modelRole;
    @XmlAttribute
    protected String simulator;

    /**
     * Gets the value of the scenarioRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScenarioRole() {
        return scenarioRole;
    }

    /**
     * Sets the value of the scenarioRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScenarioRole(String value) {
        this.scenarioRole = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the modelRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelRole() {
        return modelRole;
    }

    /**
     * Sets the value of the modelRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelRole(String value) {
        this.modelRole = value;
    }

    /**
     * Gets the value of the simulator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimulator() {
        return simulator;
    }

    /**
     * Sets the value of the simulator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimulator(String value) {
        this.simulator = value;
    }

}
