//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.31 at 07:35:14 PM BST 
//


package org.savara.scenario.simulation.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Simulation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Simulation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="roles" type="{http://www.savara.org/scenario/simulation}RoleDetails" maxOccurs="unbounded"/>
 *         &lt;element name="simulators" type="{http://www.savara.org/scenario/simulation}SimulatorDetails" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="scenario" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Simulation", propOrder = {
    "roles",
    "simulators"
})
public class Simulation {

    @XmlElement(required = true)
    protected List<RoleDetails> roles;
    @XmlElement(required = true)
    protected List<SimulatorDetails> simulators;
    @XmlAttribute
    protected String scenario;

    /**
     * Gets the value of the roles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RoleDetails }
     * 
     * 
     */
    public List<RoleDetails> getRoles() {
        if (roles == null) {
            roles = new ArrayList<RoleDetails>();
        }
        return this.roles;
    }

    /**
     * Gets the value of the simulators property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simulators property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimulators().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimulatorDetails }
     * 
     * 
     */
    public List<SimulatorDetails> getSimulators() {
        if (simulators == null) {
            simulators = new ArrayList<SimulatorDetails>();
        }
        return this.simulators;
    }

    /**
     * Gets the value of the scenario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScenario() {
        return scenario;
    }

    /**
     * Sets the value of the scenario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScenario(String value) {
        this.scenario = value;
    }

}
