
package org.savara.examples.creditagency;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-08-10T09:46:11.178+01:00
 * Generated source version: 2.4.0
 * 
 */

@WebFault(name = "CustomerUnknown", targetNamespace = "http://www.jboss.org/examples/creditAgency")
public class CustomerUnknownFault extends Exception {
    public static final long serialVersionUID = 20120810094611L;
    
    private org.jboss.examples.creditagency.CustomerUnknownType customerUnknown;

    public CustomerUnknownFault() {
        super();
    }
    
    public CustomerUnknownFault(String message) {
        super(message);
    }
    
    public CustomerUnknownFault(String message, Throwable cause) {
        super(message, cause);
    }

    public CustomerUnknownFault(String message, org.jboss.examples.creditagency.CustomerUnknownType customerUnknown) {
        super(message);
        this.customerUnknown = customerUnknown;
    }

    public CustomerUnknownFault(String message, org.jboss.examples.creditagency.CustomerUnknownType customerUnknown, Throwable cause) {
        super(message, cause);
        this.customerUnknown = customerUnknown;
    }

    public org.jboss.examples.creditagency.CustomerUnknownType getFaultInfo() {
        return this.customerUnknown;
    }
}
