/*
 * Generated by Savara.
 */
package %PACKAGE%;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import javax.xml.namespace.QName;
import javax.xml.transform.dom.DOMSource;

import org.switchyard.exception.SwitchYardException;

public class %CLASSNAME% extends org.switchyard.transform.BaseTransformer<DOMSource,%FAULTCLASS%> {

	public QName getFrom() {
		return (QName.valueOf("%FAULTQNAME%"));
	}
	
	public %FAULTCLASS% transform(DOMSource type) {
		Unmarshaller unmarshaller;
		JAXBContext _jaxbContext;

		try {
			_jaxbContext = JAXBContext.newInstance("%FAULTTYPEPACKAGE%");
		} catch (JAXBException e) {
			throw new SwitchYardException("Failed to create JAXBContext for '" + getFrom() + "'.", e);
		}

		try {
			unmarshaller = _jaxbContext.createUnmarshaller();
		} catch (JAXBException e) {
			throw new SwitchYardException("Failed to create Unmarshaller for type '" + getFrom() + "'.", e);
		}

		try {
			org.jboss.examples.creditagency.CustomerUnknownType fault=
					(org.jboss.examples.creditagency.CustomerUnknownType)unmarshaller.unmarshal(type);

			return new %FAULTCLASS%("%FAULTMESSAGE%", fault);
		} catch (Exception e) {
			throw new SwitchYardException("Failed to unmarshal fault", e);
		}
	}
}
