//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.30 at 10:01:35 PM GMT 
//


package org.savara.scenario.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.savara.scenario.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Scenario_QNAME = new QName("http://www.savara.org/scenario", "scenario");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.savara.scenario.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TimeElapsedEvent }
     * 
     */
    public TimeElapsedEvent createTimeElapsedEvent() {
        return new TimeElapsedEvent();
    }

    /**
     * Create an instance of {@link Scenario }
     * 
     */
    public Scenario createScenario() {
        return new Scenario();
    }

    /**
     * Create an instance of {@link ReceiveEvent }
     * 
     */
    public ReceiveEvent createReceiveEvent() {
        return new ReceiveEvent();
    }

    /**
     * Create an instance of {@link SendEvent }
     * 
     */
    public SendEvent createSendEvent() {
        return new SendEvent();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Import }
     * 
     */
    public Import createImport() {
        return new Import();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Scenario }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.savara.org/scenario", name = "scenario")
    public JAXBElement<Scenario> createScenario(Scenario value) {
        return new JAXBElement<Scenario>(_Scenario_QNAME, Scenario.class, null, value);
    }

}
