
/*
 * 
 */

package org.savara.purchasing.creditagency;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-09-02T18:03:55.854+01:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "CreditAgencyService", 
                  wsdlLocation = "wsdl/Purchasing_CreditAgency.wsdl",
                  targetNamespace = "http://www.savara.org/Purchasing/CreditAgency") 
public class CreditAgencyService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.savara.org/Purchasing/CreditAgency", "CreditAgencyService");
    public final static QName CreditAgencyPort = new QName("http://www.savara.org/Purchasing/CreditAgency", "CreditAgencyPort");
    static {
        URL url = null;
        try {
            url = new URL("wsdl/Purchasing_CreditAgency.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CreditAgencyService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "wsdl/Purchasing_CreditAgency.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CreditAgencyService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreditAgencyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditAgencyService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns CreditAgency
     */
    @WebEndpoint(name = "CreditAgencyPort")
    public CreditAgency getCreditAgencyPort() {
        return super.getPort(CreditAgencyPort, CreditAgency.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditAgency
     */
    @WebEndpoint(name = "CreditAgencyPort")
    public CreditAgency getCreditAgencyPort(WebServiceFeature... features) {
        return super.getPort(CreditAgencyPort, CreditAgency.class, features);
    }

}
