/*
 * Generated by Savara.
 */
package org.savara.purchasing.creditagency;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;
import javax.xml.namespace.QName;
import javax.xml.transform.dom.DOMSource;

public class CustomerUnknownFaultConsumerTransformer extends org.switchyard.transform.BaseTransformer<DOMSource,org.savara.purchasing.creditagency.CustomerUnknownFault> {

	private static final Logger LOG=Logger.getLogger(CustomerUnknownFaultConsumerTransformer.class.getName());
	
	public QName getFrom() {
		return (QName.valueOf("{http://www.jboss.org/examples/creditAgency}CustomerUnknown"));
	}
	
	public org.savara.purchasing.creditagency.CustomerUnknownFault transform(DOMSource type) {
		Unmarshaller unmarshaller;
		JAXBContext _jaxbContext;

		try {
			_jaxbContext = JAXBContext.newInstance("org.jboss.examples.creditagency");
		} catch (JAXBException e) {
			LOG.log(Level.SEVERE, "Failed to create JAXBContext for '" + getFrom() + "'.", e);
			return (null);
		}

		try {
			unmarshaller = _jaxbContext.createUnmarshaller();
		} catch (JAXBException e) {
			LOG.log(Level.SEVERE, "Failed to create Unmarshaller for type '" + getFrom() + "'.", e);
			return (null);
		}

		try {
			javax.xml.bind.JAXBElement<org.jboss.examples.creditagency.CustomerUnknownType> jbe=
						(javax.xml.bind.JAXBElement<org.jboss.examples.creditagency.CustomerUnknownType>)unmarshaller.unmarshal(type);
			
			return new org.savara.purchasing.creditagency.CustomerUnknownFault("CustomerUnknownFaultConsumerTransformer", jbe.getValue());
		} catch (Exception e) {
			LOG.log(Level.SEVERE, "Failed to unmarshal fault", e);
			return (null);
		}
	}
}
