//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.10 at 11:11:33 PM GMT 
//


package org.savara.bpel.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tAssign complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tAssign">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}tActivity">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}copy"/>
 *           &lt;element ref="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}extensionAssignOperation"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="validate" type="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}tBoolean" default="no" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAssign", propOrder = {
    "copyOrExtensionAssignOperation"
})
public class TAssign
    extends TActivity
{

    @XmlElements({
        @XmlElement(name = "copy", type = TCopy.class),
        @XmlElement(name = "extensionAssignOperation", type = TExtensionAssignOperation.class)
    })
    protected List<TExtensibleElements> copyOrExtensionAssignOperation;
    @XmlAttribute(name = "validate")
    protected TBoolean validate;

    /**
     * Gets the value of the copyOrExtensionAssignOperation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the copyOrExtensionAssignOperation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCopyOrExtensionAssignOperation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TCopy }
     * {@link TExtensionAssignOperation }
     * 
     * 
     */
    public List<TExtensibleElements> getCopyOrExtensionAssignOperation() {
        if (copyOrExtensionAssignOperation == null) {
            copyOrExtensionAssignOperation = new ArrayList<TExtensibleElements>();
        }
        return this.copyOrExtensionAssignOperation;
    }

    /**
     * Gets the value of the validate property.
     * 
     * @return
     *     possible object is
     *     {@link TBoolean }
     *     
     */
    public TBoolean getValidate() {
        if (validate == null) {
            return TBoolean.NO;
        } else {
            return validate;
        }
    }

    /**
     * Sets the value of the validate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBoolean }
     *     
     */
    public void setValidate(TBoolean value) {
        this.validate = value;
    }

}
