//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.10 at 11:11:33 PM GMT 
//


package org.savara.bpel.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tSequence complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tSequence">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}tActivity">
 *       &lt;sequence>
 *         &lt;group ref="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}activity" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tSequence", propOrder = {
    "activity"
})
public class TSequence
    extends TActivity
{

    @XmlElements({
        @XmlElement(name = "rethrow", type = TRethrow.class),
        @XmlElement(name = "compensateScope", type = TCompensateScope.class),
        @XmlElement(name = "exit", type = TExit.class),
        @XmlElement(name = "flow", type = TFlow.class),
        @XmlElement(name = "invoke", type = TInvoke.class),
        @XmlElement(name = "if", type = TIf.class),
        @XmlElement(name = "throw", type = TThrow.class),
        @XmlElement(name = "receive", type = TReceive.class),
        @XmlElement(name = "repeatUntil", type = TRepeatUntil.class),
        @XmlElement(name = "compensate", type = TCompensate.class),
        @XmlElement(name = "scope", type = TScope.class),
        @XmlElement(name = "wait", type = TWait.class),
        @XmlElement(name = "assign", type = TAssign.class),
        @XmlElement(name = "extensionActivity", type = TExtensionActivity.class),
        @XmlElement(name = "while", type = TWhile.class),
        @XmlElement(name = "sequence", type = TSequence.class),
        @XmlElement(name = "reply", type = TReply.class),
        @XmlElement(name = "validate", type = TValidate.class),
        @XmlElement(name = "empty", type = TEmpty.class),
        @XmlElement(name = "forEach", type = TForEach.class),
        @XmlElement(name = "pick", type = TPick.class)
    })
    protected List<Object> activity;

    /**
     * Gets the value of the activity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRethrow }
     * {@link TCompensateScope }
     * {@link TExit }
     * {@link TFlow }
     * {@link TInvoke }
     * {@link TIf }
     * {@link TThrow }
     * {@link TReceive }
     * {@link TRepeatUntil }
     * {@link TCompensate }
     * {@link TScope }
     * {@link TWait }
     * {@link TAssign }
     * {@link TExtensionActivity }
     * {@link TWhile }
     * {@link TSequence }
     * {@link TReply }
     * {@link TValidate }
     * {@link TEmpty }
     * {@link TForEach }
     * {@link TPick }
     * 
     * 
     */
    public List<Object> getActivity() {
        if (activity == null) {
            activity = new ArrayList<Object>();
        }
        return this.activity;
    }

}
