package org.savara.purchasing.logistics;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-09-02T18:03:53.663+01:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://www.savara.org/Purchasing/Logistics", name = "Logistics")
@XmlSeeAlso({org.jboss.examples.logistics.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Logistics {

    @WebResult(name = "DeliveryConfirmed", targetNamespace = "http://www.jboss.org/examples/logistics", partName = "content")
    @WebMethod(action = "http://www.savara.org/Purchasing/Logistics/delivery")
    public org.jboss.examples.logistics.DeliveryConfirmedType delivery(
        @WebParam(partName = "content", name = "DeliveryRequest", targetNamespace = "http://www.jboss.org/examples/logistics")
        org.jboss.examples.logistics.DeliveryRequestType content
    );
}
