
package org.jboss.examples.store;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-06-08T17:04:28.019+01:00
 * Generated source version: 2.4.0
 * 
 */

@WebFault(name = "BuyFailed", targetNamespace = "http://www.jboss.org/examples/store")
public class BuyFailedFault extends Exception {
    public static final long serialVersionUID = 20110608170428L;
    
    private org.jboss.examples.store.BuyFailedType buyFailed;

    public BuyFailedFault() {
        super();
    }
    
    public BuyFailedFault(String message) {
        super(message);
    }
    
    public BuyFailedFault(String message, Throwable cause) {
        super(message, cause);
    }

    public BuyFailedFault(String message, org.jboss.examples.store.BuyFailedType buyFailed) {
        super(message);
        this.buyFailed = buyFailed;
    }

    public BuyFailedFault(String message, org.jboss.examples.store.BuyFailedType buyFailed, Throwable cause) {
        super(message, cause);
        this.buyFailed = buyFailed;
    }

    public org.jboss.examples.store.BuyFailedType getFaultInfo() {
        return this.buyFailed;
    }
}
