
/*
 * 
 */

package org.jboss.examples.store;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-06-08T17:04:28.054+01:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "StoreService", 
                  wsdlLocation = "wsdl/PurchaseGoodsProcess_Store.wsdl",
                  targetNamespace = "http://www.jboss.org/examples/store") 
public class StoreService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.jboss.org/examples/store", "StoreService");
    public final static QName StoreInterfacePort = new QName("http://www.jboss.org/examples/store", "StoreInterfacePort");
    static {
        URL url = null;
        try {
            url = new URL("wsdl/PurchaseGoodsProcess_Store.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StoreService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "wsdl/PurchaseGoodsProcess_Store.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StoreService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StoreService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StoreService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns StoreInterface
     */
    @WebEndpoint(name = "StoreInterfacePort")
    public StoreInterface getStoreInterfacePort() {
        return super.getPort(StoreInterfacePort, StoreInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StoreInterface
     */
    @WebEndpoint(name = "StoreInterfacePort")
    public StoreInterface getStoreInterfacePort(WebServiceFeature... features) {
        return super.getPort(StoreInterfacePort, StoreInterface.class, features);
    }

}
