//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.12 at 12:36:45 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL",
xmlns = {
	    @javax.xml.bind.annotation.XmlNs(prefix = "bpmn2", namespaceURI = "http://www.omg.org/spec/BPMN/20100524/MODEL"),
	    @javax.xml.bind.annotation.XmlNs(prefix = "bpmndi", namespaceURI = "http://www.omg.org/spec/BPMN/20100524/DI"),
	    @javax.xml.bind.annotation.XmlNs(prefix = "dc", namespaceURI = "http://www.omg.org/spec/DD/20100524/DC")
	},
	elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.savara.bpmn2.model;
